[detectors]
detector_names = [
    "stereotypes",
    "harmful_content",
    "sycophancy",
    "chars_injection",
    "faithfulness",
    "implausible_output",
    "information_disclosure",
    "output_formatting",
    "prompt_injection"
]
